### ISSUE TITLE
Kmonad not enabled in GNOME lock screen

### ISSUE THREAD

**Issue by vandalt** [jurf/gnome-kmonad-toggle#6]
Hi!

When I use this extension to enable kmonad, it works for the GNOME shell, but it is not enabled on the lock screen. When I enable it via the terminal with `kmonad ~/.config/kmonad/config.kbd`, it does work on the lock screen.

Let me know if there is other info I can provide to help with this.

Thanks!

**Comment by jurf** [comment]
Hey, this is by design. GNOME extensions do not work in the lockscreen by default, cf. https://gjs.guide/extensions/overview/anatomy.html#session-modes. It can be enabled, but

- It is a potential security issue (my main reason I had not to enable it)
- Users can potentially lock themselves out of their computer with a bad config
- It has to be justified in the review process
- Kmonad/kanata would get restarted when locking/unlocking
- Could possibly add confusion, as it would not be running in GDM anyway

What is your use case? I am perfectly fine with typing in my password in QWERTY in the lockscreen, so the potential risks never outweighed the benefits for me.

**Comment by vandalt** [comment]
> Hey, this is by design. GNOME extensions do not work in the lockscreen by default.

I was not aware of that, but it makes perfect sense then.

> What is your use case? I am perfectly fine with typing in my password in QWERTY in the lockscreen, so the potential risks never outweighed the benefits for me.

My use case was using home row mods even on the lock screen for navigation/password. But in light of your explanation I agree that the risks/trouble are not worth the small benefits. Consistency with GDM is also a good point.

Thanks!
